### PR TITLE
Get freight_rates for specific country (default to all)

### PR DESCRIPTION
**Pull request by MaXer001**

### CODE REVIEW

**Comment by Hungor** [comment]
@MaXer001 @JanC89 Hereby merged
Thanks for the contribution!

**Comment by MaXer001** [comment]
I've been told I was supposed to make the change from a company account. Is it possible you could revert the change so I can push it from my company account? Sorry for the inconvenience...

**Comment by MaXer001** [comment]
@Hungor @JanC89 I've been told I was supposed to make the change from a company account. Is it possible you could revert the change so I can push it from my company account? Sorry for the inconvenience...

**Comment by JanC89** [comment]
Hi @MaXer001,

I'm afraid that's not possible. Your commit has been merged into our main track, so it's not possible to delete again. We can make a commit which will revert your commit, and then have you make a new commit from the correct account. However, this wont remove your original contribution from the history.

**Comment by Hungor** [comment]
@MaXer001 @JanC89 I am thinking to refactor it so that we have the same approach as other calls. E.g. 

```
    $data = array(
      'country' => 'DK',
    );
    print_r($label->freight_rates($data));
```

**Comment by MaXer001** [comment]
@Hungor @JanC89 Thanks for a quick reply! Alright, will it be okay if I do the refactoring from the company account?

That looks like test for invoking the method, though. Do you mean something like this:

```
    public function freight_rates($country = null){
        $params = array(
            'country' => $country
        );
        $result = $this->_make_api_call('shipments/freight_rates', false, $params);
        return $result;
    }
```
It seems like all the other methods use the inline approach, though.

**Comment by Hungor** [comment]
@MaXer001 Sure, you can make a PR from your company account. I'm thinking about below:

```
    public function freight_rates($params){
        $result = $this->_make_api_call('shipments/freight_rates', false, $params);
        return $result;
    }
```
It follows with the standard of the other methods as @JanC89 defined at the beginning.
Reference: README at the repository https://github.com/pakkelabels/pakkelabels-php-sdk

**Comment by MaXer001** [comment]
@Hungor @JanC89 Thanks!

Sure, I'll do it like that if that's what you want. I just thought it would over-complicate the method, since there is only one possible parameter to set..

**Pull request merged**
